# This is a basic workflow to help you get started with Actions

name: Push to github pages

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  update_github_pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update github pages page with content
        uses: lemurp/push-files-to-another-repository@v1.0.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          # Files to be pushed to the destination repository. Accepts multiple filenames and globbing.
          source-files: index.html
          # Name of the destination username/organization
          destination-github-username: lemurp
          # Destination repository
          destination-repository-name: lemurp.github.io
          # Email for the git commit
          user-email: lemurp@github.com 
